Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 21, in <module>
    a = Rectangle()
TypeError: Rectangle.__init__() missing 2 required positional arguments: 'side' and 'area'

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 21, in <module>
    a = Rectangle()
TypeError: Rectangle.__init__() missing 1 required positional argument: 'side'

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 22, in <module>
    print('사각형의 변 or 원 반지름: ', side)
NameError: name 'side' is not defined. Did you mean: 'slice'?

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 22, in <module>
    print('사각형의 변 or 원 반지름: ', side)
NameError: name 'side' is not defined. Did you mean: 'slice'?

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 22, in <module>
    print('사각형의 변 or 원 반지름: ', self._s)
NameError: name 'self' is not defined

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 23, in <module>
    print('사각형의 변 or 원 반지름: ', self._s)
NameError: name 'self' is not defined

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 23, in <module>
    a.getArea()
TypeError: Rectangle.getArea() missing 1 required positional argument: 'side'

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
Traceback (most recent call last):
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 23, in <module>
    a.getArea()
  File "C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py", line 18, in getArea
    self._area = side * 2
NameError: name 'side' is not defined. Did you mean: 'slice'?

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름:  10
사각형의 면적:  20

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름:  10
사각형을 그립니다
사각형의 면적:  100

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름: 16
사각형을 그립니다
사각형의 면적:  100

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름: 16
사각형을 그립니다
사각형의 면적:  256

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름: 16
사각형을 그립니다
사각형의 면적: 256.00

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름: 16
사각형을 그립니다
사각형의 면적: 256.00
원을 그립니다
원의 면적: 804.35

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름: 16

원을 그립니다
원의 면적: 804.35

사각형을 그립니다
사각형의 면적: 256.00

원을 그립니다
원의 면적: 804.35

= RESTART: C:/Users/H P/Desktop/1학년 - 2/컴프 - 파이썬/1118/1118-2022320071-아이샤-과제-1.py
사각형의 변 or 원 반지름: 10

원을 그립니다
원의 면적: 314.20

사각형을 그립니다
사각형의 면적: 100.00
